### ISSUE TITLE
About the input format

### ISSUE THREAD

**Issue by kugwzk** [ecchochan/roberta-tpu#2]
Hi, very thx for your work on fine-tune RoBERTa on SQuAD.
But I have a question about why you put the passage before the question in model input? Because I see the original BERT is use <CLS> Q <SEP> P format and I couldn't find anything about the SQuAD input format in RoBERT paper...

**Comment by ecchochan** [comment]
I tried **both representations** using the original BERT on SQuAD 2.0, and `P-Q` representation is slightly better than `Q-P` one.

Btw, I tried again just now to make sure! 

---

### ** I just ran the fine-tuning once, so I cannot conclude which one is better. **

---

**Input representation:** `<s> Q: Question here? </s> Passage here. </s>`
```c
lr_decay=0.75
LR=3.0e-05
batch_size=48
```

```json
{
  "exact": 85.95974058788849,
  "f1": 88.91452746948198,
  "total": 11873,
  "HasAns_exact": 84.66599190283401,
  "HasAns_f1": 90.5840392451353,
  "HasAns_total": 5928,
  "NoAns_exact": 87.24978973927671,
  "NoAns_f1": 87.24978973927671,
  "NoAns_total": 5945,
  "best_exact": 86.71776299166176,
  "best_exact_thresh": -1.505859375,
  "best_f1": 89.51793302950927,
  "best_f1_thresh": -1.505859375
}
```

**Comment by kugwzk** [comment]
Very thanks, I will try this later.

**Comment by tbright17** [comment]
Hi, thanks again for sharing the code. I'm wondering how you prepare the input data qa_records_squad_q, did you use multiprocessing_bpe_encoder followed by fairseq-preprocess?

**Comment by ecchochan** [comment]
uploaded `create_data.ipynb`
