### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './roberta.large/encoder.json'

### ISSUE THREAD

**Issue by fanyou12** [ecchochan/roberta-tpu#3]
What is the content of the encoder.json?
Can you provide source code of tokenier？

**Comment by studiocardo** [comment]
Hi nangeblog

Were you able to resolve the encoder.json and tokenizer errors?  I'm just getting started and I am encountering the same err msgs.  So I'm hoping to tap into your experience...  Any input is appreciated!

Best,
SH

**Comment by ecchochan** [comment]
The folder `roberta.large` is just the same from the original model. Please check the original repo!
https://github.com/pytorch/fairseq/tree/master/examples/roberta

uploaded `create_data.ipynb`, I hope you will find it useful!

**Comment by Winggi** [comment]
I uploaded `create_data.ipynb`, but the problem still exists when running the `create_data.ipynb`:
_FileNotFoundError: [Errno 2] No such file or directory: '/data/fairseq/roberta.large/encoder.json'_

The roberta model file only contains `model.pt` and `dict.txt`. How can I get `encoder.json`?

**Comment by Winggi** [comment]
The problem still exists when running the create_data.ipynb:
FileNotFoundError: [Errno 2] No such file or directory: '/data/fairseq/roberta.large/encoder.json'

The roberta model file only contains model.pt and dict.txt. How can I get encoder.json?

**Comment by Winggi** [comment]
The problem still exists when running the `create_data.ipynb`:

_FileNotFoundError: [Errno 2] No such file or directory: '/data/fairseq/roberta.large/encoder.json'_

The roberta model file only contains `model.pt` and `dict.txt`. How can I get `encoder.json`?
